# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mp3_download_request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amp3_download_request.proto\"i\n\x12MP3DownloadRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x12\n\nepisode_id\x18\x02 \x01(\t\x12\x18\n\x0b\x65pisode_url\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_episode_urlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mp3_download_request_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MP3DOWNLOADREQUEST']._serialized_start=30
  _globals['_MP3DOWNLOADREQUEST']._serialized_end=135
# @@protoc_insertion_point(module_scope)
